server:
  # 设置端口号
  port: 8001
spring:
  # 导入相关的配置文件
  config:
    import: classpath:config/knife4j.yml, config/db.yml # 导入配置文件
#  profiles:
#    active: dev # 当前的配置文件
  jackson: # # 处理返回的日期格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8