# mysql
spring:
  datasource:
    # druid
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SpringCloud
    username: root
    password: GDB20031104!
# mybatis
mybatis:
  config-location: classpath:config/mybatis-config.xml