server:
  port: 80
spring:
  config:
    # 导入其他的配置文件
    import: openfeign.yml,consul.yml
  # todo 不知道为什么这里现在需要加上对时间的处理了，之前调用另外一个服务的时候都不需要的，现在使用OpenFeign就出现了日期无法转换的问题了。
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
