spring:
  application:
    name: cloud-consumer-resilience4j-order
  cloud:
    # 配置consul
    consul:
      # consul 所在的IP地址
      host: localhost
      # consul 所在的端口号
      port: 8500
      discovery:
        # 服务以什么名字注册到 consul 中
        service-name: ${spring.application.name}
        # 优先使用服务 IP 进行注册
        #        prefer-ip-address: true
        # 开启心跳模式，如果不开启服务注册后一直是红×
        heartbeat:
          enabled: true