server:
  port: 80
spring:
  application:
    name: cloud-consumer-feign-order
  cloud:
    # 配置consul
    consul:
      # consul 所在的IP地址
      host: localhost
      # consul 所在的端口号
      port: 8500
      discovery:
        # 服务以什么名字注册到 consul 中
        service-name: ${spring.application.name}
        # 优先使用服务 IP 进行注册
        prefer-ip-address: true
        # 开启心跳模式，如果不开启服务注册后一直是红×
        heartbeat:
          enabled: true
  # todo 不知道为什么这里现在需要加上对时间的处理了，之前调用另外一个服务的时候都不需要的，现在使用OpenFeign就出现了日期无法转换的问题了。
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8